name: o3d
channels:
  # You can use the TUNA mirror to speed up the installation if you are in mainland China.
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7.9
  - pytorch=1.8.0
  - torchvision=0.9.0
  - cudatoolkit=11.1
  - ipython
  - tqdm
  - numba
  - matplotlib
  - pip
  - pip: 
    - open3d==0.13.0